# Generated by Django 5.1 on 2024-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='お名前')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('email', models.EmailField(max_length=254, verbose_name='連絡先メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('content', models.TextField(verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='問い合わせ日時')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ一覧',
            },
        ),
    ]
