# Generated by Django 5.1 on 2024-09-01 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='会社コード')),
                ('name', models.CharField(max_length=150, verbose_name='会社名')),
                ('is_active', models.BooleanField(default=True, verbose_name='アカウント有効')),
                ('membership_type', models.CharField(choices=[('0', '無料会員'), ('1', 'ライト'), ('2', 'スタンダード'), ('3', 'エンタープライズ')], max_length=36, verbose_name='会員種別')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社一覧',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='お名前')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('email', models.EmailField(max_length=254, verbose_name='連絡先メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('content', models.TextField(verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='問い合わせ日時')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ一覧',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('personal', 'あなたへのお知らせ'), ('product', 'プロダクト情報'), ('mebias', 'Me-Biasからのご案内')], max_length=20, verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ一覧',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='アカウント有効')),
                ('user_type', models.CharField(choices=[('superuser', 'スーパーユーザー'), ('admin', '管理者ユーザー'), ('user', '一般ユーザー')], default='user', max_length=20, verbose_name='ユーザー種別')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'お知らせ既読',
                'verbose_name_plural': 'お知らせ既読一覧',
            },
        ),
    ]
